default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost

development:
  <<: *default
  database: hardlib_dev

test: &test
  <<: *default
  database: hardlib_test

cucumber:
  <<: *test
