development:
  secret_key_base: 5bcbf6200bc710925155cba447fabc978a1e973675a3fbd5707ace93b30bfbac51c16eb8b72d36f11ac2e8b4e017fdd75be59bc0b9f3e5114e5fdfe2cafa56ee
  google_storage_access_key_id: <%= ENV['GOOGLE_STORAGE_ACCESS_KEY_ID'] %>
  google_storage_secret_access_key: <%= ENV['GOOGLE_STORAGE_SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: b1ddbc6732499179159abf15802f6aa497844869c93cfa49a0a1ef3f3f26273ce087395c9305b48e98b8b993534df761b4e857eb992a55e1dbe172021ca4704d

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  google_storage_access_key_id: <%= ENV['GOOGLE_STORAGE_ACCESS_KEY_ID'] %>
  google_storage_secret_access_key: <%= ENV['GOOGLE_STORAGE_SECRET_ACCESS_KEY'] %>
