# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bcbf6200bc710925155cba447fabc978a1e973675a3fbd5707ace93b30bfbac51c16eb8b72d36f11ac2e8b4e017fdd75be59bc0b9f3e5114e5fdfe2cafa56ee
  google_storage_access_key_id: <%= ENV['GOOGLE_STORAGE_ACCESS_KEY_ID'] %>
  google_storage_secret_access_key: <%= ENV['GOOGLE_STORAGE_SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: b1ddbc6732499179159abf15802f6aa497844869c93cfa49a0a1ef3f3f26273ce087395c9305b48e98b8b993534df761b4e857eb992a55e1dbe172021ca4704d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
